// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuuuncjhsyqzsgnerojy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51dXVuY2poc3lxenNnbmVyb2p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNDE3NDQsImV4cCI6MjA2NzcxNzc0NH0.AdIlfO6PvSqEZRaOzpozIbOiqLDO6yIMAlpuS5dkwJE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});